defaults:
- override hydra/sweeper: orion

hydra:
    sweeper:
       params:
          lr: "loguniform(1e-5, 1.0)"
       orion:
          name: 'experiment'
          version: '1'

       algorithm:
          type: random
          config:
             seed: 1

       worker:
          n_workers: -1
          max_broken: 3
          max_trials: 1

       storage:
          type: legacy
          database:
             type: pickleddb
             host: 'database.pkl'
#Default value
lr: 0.01

args:
   size_train_dataset:
   size_eval_dataset:
   freeze_base_model:
   per_device_train_batch_size:
   optim:
   weight_decay:
   adam_beta1:
   adam_beta2:
   adam_epsilon:
   logfile:
   learning_rate: ${lr}
   num_train_epochs: 1