package:
  name: orion
  version: {{ environ.get('GIT_DESCRIBE_TAG', 'unknown').lstrip('v') }}

source:
  path: ../

build:
  script: pip install . --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python }}
    - pip
    - hatchling
    - hatch-vcs
    - appdirs
  run:
    - cloudpickle
    - python
    - numpy
    - scipy
    - pyyaml
    - pymongo >=3
    - gitpython
    - filelock
    - tabulate
    - AppDirs
    - plotly
    - python-kaleido ==0.2.1
    - requests
    - pandas
    - falcon >=4,<5
    - falcon-cors
    - gunicorn
    - scikit-learn
    - psutil
    - scikit-optimize

test:
  import:
    - orion.algo
    - orion.client
    - orion.core
    - orion.core.cli
    - orion.serving
    - orion.storage
    - orion.testing
  commands:
    - orion --help

about:
  home: http://github.com/epistimio/orion
  license: BSD
  license_file: LICENSE
