{% set version = os.popen("python -c 'import versioneer; print(versioneer.get_version())'").read() %}

package:
  name: orion
  version: {{ version }}

source:
  path: ../

build:
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python {{ python }}
    - setuptools
    - pytest-runner
    - appdirs
  run:
    - dataclasses
    - python
    - numpy
    - scipy
    - pyyaml
    - pymongo >=3
    - gitpython
    - filelock
    - tabulate
    - AppDirs
    - plotly
    - python-kaleido
    - requests
    - pandas
    - falcon
    - gunicorn
    - scikit-learn
    - psutil
    - pytest >=3.0.0

test:
  import:
    - orion.algo
    - orion.client
    - orion.core
    - orion.core.cli
    - orion.serving
    - orion.storage
    - orion.testing
  commands:
    - orion --help

about:
  home: http://github.com/epistimio/orion
  license: BSD
  license_file: LICENSE
