#!/usr/bin/env python
# -*- coding: utf-8 -*-
from __future__ import print_function, absolute_import

from metaopt.io import parsing

MOPT_DESCRIPTION = """\
mopt:
  MetaOpt cli script for asynchronous distributed optimization
"""

if __name__ == '__main__':
    # Fetch experiment name, user's script, args and parameter config
    # Use `-h` option to
    expconfig = parsing.mopt_args(MOPT_DESCRIPTION)
    # TODO load defaults here...
    # Fetch mopt system variables (e.g. database information)
    # See metaopt.io.parsing.MOPT_ENV_VARS for environmental variables used
    expconfig = parsing.env_vars(expconfig)
    # Fetch options for optimization and auto stopping method to be used
    # See inside `config` at metaopt's root directory for all possible options
    expconfig = parsing.mopt_config(expconfig)
    # TODO check database here, but decide on database

    print(expconfig)
    if expconfig['userconfig']:
        print(expconfig['userconfig'])
