name: orion-tests

on: [push]

jobs:
  orion-docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: cache-pip
        uses: actions/cache@v1
        with:
          path: .tox
          key: ${{ runner.OS }}-build-${{ hashFiles('setup.py') }}
          restore-keys: |
            ${{ runner.OS }}-build-${{ env.cache-name }}-
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-

      - name: docs
        run: |
          python -m pip install --upgrade pip
          pip install wheel
          pip install tox

          TOXENV=docs tox

      - name: doc8
        run: |
          TOXENV=doc8 tox

  orion-flake8:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: cache-pip
        uses: actions/cache@v1
        with:
          path: .tox
          key: ${{ runner.OS }}-build-${{ hashFiles('setup.py') }}
          restore-keys: |
            ${{ runner.OS }}-build-${{ env.cache-name }}-
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-

      - name: flake8
        run: |
          python -m pip install --upgrade pip
          pip install wheel
          pip install tox

          TOXENV=flake8 tox

  orion-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: cache-pip
        uses: actions/cache@v1
        with:
          path: .tox
          key: ${{ runner.OS }}-build-${{ hashFiles('setup.py') }}
          restore-keys: |
            ${{ runner.OS }}-build-${{ env.cache-name }}-
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-

      - name: pylint
        run: |
          python -m pip install --upgrade pip
          pip install wheel
          pip install tox

          TOXENV=pylint tox

  orion-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install mongo
      run: |
        sudo apt-get update
        sudo apt-get install mongodb mongodb-clients

    - name: cache-pip
      uses: actions/cache@v1
      with:
        path: .tox
        key: ${{ runner.OS }}-build-${{ hashFiles('setup.py') }}
        restore-keys: |
          ${{ runner.OS }}-build-${{ env.cache-name }}-
          ${{ runner.OS }}-build-
          ${{ runner.OS }}-

    - name: units
      run: |
        python -m pip install --upgrade pip
        pip install wheel
        pip install tox

        mongo orion_test --eval 'db.createUser({user:"user",pwd:"pass",roles:["readWrite"]});'
        TOXENV=py37 tox

        tox -e final-coverage
