name: orion-CI

on: [push]

jobs:
  orion-ci:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: cache-pip
      uses: actions/cache@v1
      with:
        path: venv
        key: ${{ runner.OS }}-build-${{ hashFiles('setup.py') }}
        restore-keys: |
          ${{ runner.OS }}-build-${{ env.cache-name }}-
          ${{ runner.OS }}-build-
          ${{ runner.OS }}-

    - name: flake8
      run: |
        pip install virtualenv tox
        python -m venv venv
        . venv/bin/activate
        TOXENV=flake8 tox

